include:
  - project: repos/m3api/ci-templates
    file: /test+release.yml

stages:
  - test
  - release
  - publish-docs

test-job:
  extends: .test-job

test-package-lock-job:
  extends: .test-package-lock-job

release-job:
  extends: .release-job

publish-job:
  extends: .publish-job

doc-job:
  extends: .doc-job

publish-doc-job:
  extends: .publish-doc-job
